// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/DB/runGoogleAuth.tsx";
import * as $1 from "./routes/_middleware.tsx";
import * as $2 from "./routes/admin/main.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Admin.tsx";
import * as $$1 from "./islands/Entry.tsx";
import * as $$2 from "./islands/Relso.tsx";

const manifest = {
  routes: {
    "./routes/DB/runGoogleAuth.tsx": $0,
    "./routes/_middleware.tsx": $1,
    "./routes/admin/main.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Admin.tsx": $$0,
    "./islands/Entry.tsx": $$1,
    "./islands/Relso.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
